### ISSUE TITLE
An internal DaCe error was encountered! (DaCe request failed with code 500)

### ISSUE THREAD

**Issue by nyctophile-1302** [spcl/dace-vscode#170] opened 2022-07-01 06:33 UTC
I tried importing .py file via the extension but it gives the mentioned error

**Comment by phschaad** [comment] 2022-07-01 09:19
Thank you for opening the issue! I assume you're referring to importing a custom transformation?

**Comment by phschaad** [comment] 2022-07-04 15:36
If you navigate to the VSCode terminal, there should be a terminal called 'SDFG Optimizer'. This terminal should contain a detailed stack trace of the error when it occurs. Could you paste that trace here?
(Better error reporting is under way https://github.com/spcl/dace-vscode/issues/172)

**Comment by nyctophile-1302** [comment] 2022-07-04 16:00
File "C:\Users\aryas\AppData\Local\Programs\Python\Python310\lib\site-packages\dace\properties.py", line 389, in initialize_properties
    init(obj, *args, **kwargs)
  File "C:\Users\aryas\AppData\Local\Programs\Python\Python310\lib\site-packages\dace\sdfg\sdfg.py", line 347, in __init__
    raise InvalidSDFGError('Invalid SDFG name "%s"' % name, self, None)
dace.sdfg.validation.InvalidSDFGError: Invalid SDFG name "e:\New folder\gemm_py_getstarted"
[2022-07-04 21:29:31,785] INFO in _internal: 127.0.0.1 - - [04/Jul/2022 21:29:31] "POST /add_transformations HTTP/1.1" 500 -


This is the terminal what the terminal shows.

**Comment by phschaad** [comment] 2022-07-04 16:52
The error seems to suggest that an SDFG is being loaded and fails validation, does the file with the transformation you wanted to add contain other code besides the transformation definition?

**Comment by nyctophile-1302** [comment] 2022-07-04 18:14
`import dace

@dace.program
def getstarted(A):
    return A + A

import numpy as np
a = np.random.rand(2, 3)
a

getstarted.to_sdfg(a)`

This is the code in the file. Have I added something extra here?

**Comment by phschaad** [comment] 2022-07-04 18:36
Thank you for the provided details!

It seems that you loaded a file that doesn't contain a graph transformation, but an SDFG (or DaCe program). I believe you were trying to run this DaCe program and view the resulting SDFG? If so, I recommend opening the file normally through VSCode (`File > Open File` in the top menu, or `Ctrl. + O`). You can use `getstarted.to_sdfg(a).view()` to have the generated SDFG be opened automatically in your editor and explore it:

![tmp](https://user-images.githubusercontent.com/9193712/177204441-022a212f-e249-4788-abaa-acc20db4654c.gif)

Alternatively, you can use `getstarted.to_sdfg(a).save('path/to/my/program.sdfg')` to save the SDFG to a file, which you can then open using the standard VSCode `File > Open File` method again to see your SDFG.

If you were indeed trying to write a custom transformation, that would be the correct button to load said transformation. You can find more information on how to write custom transformations [here](https://nbviewer.org/github/spcl/dace/blob/master/tutorials/transformations.ipynb#Creating-New-Transformations).

Does this address your problem?

**Comment by phschaad** [comment] 2022-08-06 10:00
The latest [insider pre-release](https://github.com/spcl/dace-vscode/releases/tag/v1.3.1-insider) provides much better error reporting from the DaCe daemon. In case this issue has not been resolved yet, I suggest using the mentioned pre-release to see whether a) it addresses the problem, or b) whether a more detailed error message is generated.

I will close this issue for now, please let me know if the problem is not resolved yet.

**Closed by phschaad** 2022-08-06 10:00 UTC
Labels: question
